config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get "/about",   to: "home#about"
  get "/help", to: "home#help"
  get "/contact", to: "home#contact"
  get "/terms", to: "home#terms"
  get "/signup",  to: "users#new"
  get "/signup", to: "users#create"
  get '/login', to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/search", to: "posts#search"

  resources :users, except: [:new, :create]

  resources :users do
    resource :password, except: [:index, :create, :new, :show , :destroy]
    resource :following, only: [:show]
    resource :follower, only: [:show]
    # member do
    #   get :following, :followers
    # end
  end

  resources :posts, except: [:index, :destroy] do
    resource :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: :index

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }

    has_many :posts, dependent: :destroy

    has_many :likes, dependent: :destroy

    has_many :liked_posts, through: :likes,  source: :post

    has_many :comments, dependent: :destroy

    has_many :active_relationships,  class_name: "Relationship",
                                     foreign_key: "follower_id",
                                     dependent: :destroy
    has_many :passive_relationships, class_name:  "Relationship",
                                     foreign_key: "followed_id",
                                     dependent: :destroy
    
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower

    has_many :active_notifications, class_name: 'Notification',
                                    foreign_key: "visitor_id",
                                    dependent: :destroy
    has_many :passive_notifications, class_name: 'Notification',
                                     foreign_key: "visited_id",
                                     dependent: :destroy

    has_secure_password

    # 画像アップロード実装(carrierwave)
    mount_uploader :image, ImageUploader

    validates :name ,    presence: { message: "を入力してください。"},
                         length: { maximum: 20 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email,    presence: { message: "を入力してください。"},
                         length: { maximum: 255 },
                         format: { with: VALID_EMAIL_REGEX },
                         uniqueness: { case_sensitive: false }

    validates :password, presence: true,
                         length: { minimum: 6},
                         allow_nil: true
    # validates :password_confirmation, presence: true, allow_nil: true
    validates :username, presence: true,
                         allow_nil: true,
                         length: { maximum: 20 }

    VALID_TELL_PHONE = /\A0[56789]0[-]?\d{4}[-]?\d{4}\z/
    validates :tell_number, format: { with: VALID_TELL_PHONE },
                            allow_blank: true

    validates :website,  length: { maximum: 255 }

    validates :self_introduce, length: { maximum: 300}

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end


    def feed
        Post.where("user_id = ?", id)
    end

    def follow(other_user)
        following << other_user
    end

    def unfollow(other_user)
        active_relationships.find_by(followed_id: other_user.id).destroy
    end

    def following?(other_user)
        following.include?(other_user)
    end

    def liked(post)
        liked_posts << post
    end

    def unliked(post)
        likes.find_by(post_id: post.id).destroy
    end

    def like?(post)
        liked_posts.include?(post)
    end

    def create_notification_follow!(current_user)
      temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])

      if temp.blank?
        notification = current_user.active_notifications.new(visited_id: id,
                                                             action: 'follow')
        notification.save if notification.valid?
      end
    end


    def feed
      following_ids = "SELECT followed_id FROM relationships
                      WHERE follower_id = :user_id"           
      Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
    end


    # def self.find_for_oauth(auth)
    #     user = User.where(uid: auth.uid, provider: auth.provider).first
    
    #     unless user
    #       user = User.create(
    #         uid:      auth.uid,
    #         provider: auth.provider,
    #         email:    User.dummy_email(auth),
    #         password: Devise.friendly_token[0, 20]
    #       )
    #     end
    
    #     user
    #   end
    
      private
    
      def self.dummy_email(auth)
        "#{auth.uid}-#{auth.provider}@example.com"
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update,
                                        :destroy, :following, :followers]
  before_action :correct_user, only:   [:edit, :update, :destroy]
  before_action :correct_user_with_follow_function, only: [:following, :followers]

  def index
    @users = User.all
    @posts = Post.all
  end

  def new
      @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts
  end

  def create
      @user = User.new(users_params)
      if @user.save
        log_in @user
        flash[:success] = "Created your account！"
        redirect_to @user
      else
        flash.now[:danger] = "falied to create your account…"
        render "new"
      end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(users_params)
      flash[:success] = "updated your information successfully!"
      redirect_to root_url
    else
      render "users/edit"
    end
  end
  
  def destroy
    @user = User.find_by(id: params[:id])
    if @user.destroy
      flash[:success] = "Deleted your account successfully!"
      redirect_to root_url
    else
      flash[:danger] = "failed to delete your account..."
      render root_path
    end
  end


  # def following
  #   @user = User.find_by(id: params[:id])
  #   @users = @user.following
  #   render 'relationships/following'
  # end

  # def followers
  #   @user = User.find(params[:id])
  #   @users = @user.followers
  #   render "relationships/followers"
  # end

  

  private
    
    def users_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                   :username, :website, :self_introduce,
                                   :tell_number, :image, :sex)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user? @user
    end

    def correct_user_with_follow_function
      if current_user
        @user = User.find_by(id: params[:id])
        redirect_to user_path(current_user) unless current_user? @user
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
    
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "フォローする", class: "btn btn-primary btn-width" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow'%>
        <% else %>
            <%= render 'follow'%>
        <% end %>
    </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-width" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit")%>
<div class="container">
    <%= form_with(model: @user) do |f| %>
        <%= render 'shared/@user_error_messages' %>
            <div class="form-wrapper">
                <ul>
                    <li class="form-label">
                        <%= f.label :name, "Name" %>
                    </li>
                    <li class="form-blank">
                        <%= f.text_field :name, class: "form", placeholder: "Name" %>
                    </li>
                    <li class="form-label">
                        <%= f.label :username, "UserName" %>
                    </li>
                    <li class="form-blank">
                        <%= f.text_field :username, class: "form", placeholder: "UserName"%>
                    </li>
                    <li class="form-label">
                        <%= f.label :website, "Website" %>
                    </li>
                    <li class="form-blank">
                        <%= f.text_field :website, class: "form", placeholder: "Website"%>
                    </li>
                    <li class="form-label">
                        <%= f.label :self_introduce, "Self Introduction"%>
                    </li>
                    <li class="form-blank">
                        <%= f.text_area :self_introduce, class: "form", placeholder: "Slef Introduction"%>
                    </li>
                    <li class="form-label">
                        <%= f.label :email, "Email"%>
                    </li>
                    <li class="form-blank">
                        <%= f.text_field :email, class: "form", placeholder: "email"%>
                    </li>
                    <li class="form-label">
                        <%= f.label :tell_number, "Tell Number"%>
                    </li>
                    <li class="form-blank">
                        <%= f.text_field :tell_number, class: "form", placeholder: "Tell Number"%>
                    </li>
                    <li class="form-label">
                        <%= f.label :sex, "Sex" %>
                    </li>
                    <li class="form-blank">
                        <span class="radio-button">
                            <%= f.radio_button :sex, "男", :checked => true %>male
                        </span>
                        <span class="radio-button">
                            <%= f.radio_button :sex, "女" %>female
                        </span>
                    </li>

                    <div class="form-label">Profile Icon</div>
                    <li>
                        <%= f.label :image, "アイコンを選択する", class: "btn-primary image-label fas fa-file-upload" %>
                    </li>
                    <li class="file-selection">
                        <%= f.file_field :image %>
                    </li>
                    <li >
                        <%= f.submit "submit" , class: "btn btn-primary submit"%>
                    </li>
                </ul>
            </div>
    <% end %>
    <div>
        <%= link_to "パスワード変更", edit_user_password_path(@user)  %>
    </div>
    <% if current_user? @user %>
        <div>
            <%= button_to "アカウント削除", user_path(@user), method: :delete, class: "account-delete", data: {confirm: "本当に削除しますか"} %>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
  <div class="container">
    <div class="users">
      <% @users.each do |user| %>
        <div class="user">
          <%= link_to user.username, user %>
          <div>
            <% if user.image? %>
              <%= link_to image_tag(user.image.url, class: "image-size"), user_path(user) %>
            <% else %>
              <%= link_to image_tag("アイコン.jpg", class: "image-size"), user_path(user) %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<%= render 'shared/jquery_with_login' %>
<div class="container">
  <%= form_with(model: @user) do |f| %>
    <%= render 'shared/@user_error_messages' %>
    <div class="form-wrapper form-wrapper-center">
      <ul>
        <li class="form-label">
          <%= f.label :name, "FullName" %>
        </li>
        <li>
          <%= f.text_field :name, class: "form", placeholder: "Full Name" %>
        </li>
        <li class="form-label">
          <%= f.label :username, "UserName" %>
        </li>
        <li>
          <%= f.text_field :username, class: "form", placeholder: "User Name" %>
        </li>
        <li class="form-label">
          <%= f.label :email, "Email" %>
        </li>
        <li>
          <%= f.email_field :email, class: "form", placeholder: "example@example.com" %>
        </li>
        <li class="form-label">
          <%= f.label :password, "Password" %>
        </li>
        <li>
          <%= f.password_field :password, class: "form", placeholder: "password" %>
        </li>
        <li class="form-label">
          <%= f.label :password_confirmation %>
        </li>
        <li>
          <%= f.password_field :password_confirmation, class: "form", placeholder: "password" %>
        </li>
        <li >
          <%= f.submit "submit" , class: "submit btn"%>
        </li>
      </ul>
    </div>
  <% end %>
  <div class="terms">
    <%= link_to "利用規約", terms_path %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="container">
    <div class="user-wrapper row">
        <div class="user-icon col-xs-6">
            <div class="user-name">
                <%= @user.username %>
                <% if @user.image? %>
                    <%= image_tag @user.image.url, class: "image-size image-size-profile-page" %>
                <% else %>
                    <%= image_tag "アイコン.jpg", class: "image-size image-size-profile-page" %>
                <% end %>
            </div>
            <div class="user-profile-edit">
                <%if logged_in? %>
                    <% if current_user?(@user) %>
                        <%= link_to "プロフィールを編集する", edit_user_path(@user) %>
                    <% end %>
                <% end %>
            </div>
        </div>
        <div class="follow_button col-xs-6">
            <div class="posts-count" >
                <%= "#{@posts.count}件の投稿" %>
            </div>
            <%= render 'shared/stats' %>
            <%= render 'follow_form' if logged_in? %>
        </div>
    </div>
    <div class="row">
        <div class="self-introduce-wrapper col-md-12">
            <%= @user.self_introduce %>
        </div>
    </div>
    <div class="row row-image-wrapper">
        <% @posts.each do |post| %>
            <div class="col-md-4" id="modal-photo">
                <%= link_to image_tag(post.photo.url , class: "row-image"), post %>
            </div>
        <% end %>
    </div>
</div>