config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get "/about",   to: "home#about"
  get "/help", to: "home#help"
  get "/contact", to: "home#contact"
  get "/terms", to: "home#terms"
  get "/signup",  to: "users#new"
  get "/signup", to: "users#create"
  get '/login', to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/search", to: "posts#search"

  resources :users, except: [:new, :create]

  resources :users do
    resource :password, except: [:index, :create, :new, :show , :destroy]
    resource :following, only: [:show]
    resource :follower, only: [:show]
    # member do
    #   get :following, :followers
    # end
  end

  resources :posts, except: [:index, :destroy] do
    resource :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: :index

end

app/views/shared/_@post_error_messages.html.erb
<% if @post.errors.any? %>
  <div class="error_messages-wrapper">
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li class="error-message">・<%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_@user_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_messages-wrapper">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li class="error-message">・<%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_messages-wrapper">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li class="error-message">・<%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
    <div class="footer">
      <p>&copy;PhotoTime</p>
      <% if !logged_in? %>
        <ul class="footer-list">
          <li><%= link_to "About", "/about", class: "footer-link"%></li>
          <li><%= link_to "Help", help_path, class: "footer-link"%></li>
          <li><%= link_to "Contact", "/contact", class: "footer-link" %></li>
        </ul>
      <% end %>
    </div>
</div>

app/views/shared/_header.html.erb
<div class="header-background">
  <div class="container">
    <div class="header">
      <h1 class="photo" >
        <% if logged_in? %>
          <%= link_to "PhotoTime", root_path , class: "photo-title" %>
        <% else %>
          <%= link_to "PhotoTime", root_path, class: "photo-title" %>
        <% end %>
      </h1>
      
      
        <ul class="header-right1">
          <% if logged_in? %>
            <li>
              <%= link_to "Profile", current_user , class: "header-link" %>
            </li>
            <li>
              <%= link_to "Post", new_post_path, class: "header-link" %>
            </li>
            <li>
              <% if unchecked_notifications.any? %>
                <%= link_to "Notice", notifications_path, class: "unchecked" %>
              <% else %>
                <%= link_to "Notice", notifications_path, class: "header-link" %>
              <% end %>
            </li>
            <li>
              <%= button_to "Log out", logout_path, method: :delete , class: "header-link button"%>
            </li>
            <li>
              <%= form_with url: search_path, method: :get, class: "serach-form", local: true do |f| %>
                <%= text_field_tag :search, nil, class: "search-field" %><%= f.submit 'Search', class: "search-text" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign up", signup_path,class: "header-link"%>
            </li>
            <li>
              <%= link_to "Log in", login_path,class: "header-link"%>
            </li>
            <li>
              <%= form_with url: search_path, method: :get, class: "serach-form", local: true do |f| %>
                <%= text_field_tag :search, nil, class: "search-field" %><%= f.submit 'Search', class: "search-text" %>
              <% end %>
            </li>
          <% end %>
        </ul>

        <i class="fas fa-bars bars-icon"></i>
        <ul class="header-right2">
          
            <% if logged_in? %>
              <li>
                <%= link_to "Profile", current_user , class: "header-link" %>
              </li>
              <li>
                <%= link_to "Post", new_post_path, class: "header-link" %>
              </li>
              <li>
                <% if unchecked_notifications.any? %>
                  <%= link_to "Notice", notifications_path, class: "unchecked" %>
                <% else %>
                  <%= link_to "Notice", notifications_path, class: "header-link" %>
                <% end %>
              </li>
              <li>
                <%= button_to "Log out", logout_path, method: :delete , class: "header-link button"%>
              </li>
              <li>
                <%= form_with url: search_path, method: :get, class: "serach-form", local: true do |f| %>
                  <%= text_field_tag :search, nil, class: "search-field" %><%= f.submit 'Search', class: "search-text" %>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to "Sign up", signup_path,class: "header-link"%>
              </li>
              <li>
                <%= link_to "Log in", login_path,class: "header-link"%>
              </li>
              <li>
                <%= form_with url: search_path, method: :get, class: "serach-form", local: true do |f| %>
                  <%= text_field_tag :search, nil, class: "search-field" %><%= f.submit 'Search', class: "search-text" %>
                <% end %>
              </li>
            <% end %>
        </ul>
        
        <i class="far fa-window-close"></i>
    </div>
  </div>
</div>

app/views/shared/_jquery_with_login.html.erb
    <div class="image" id="fadeout-image">
        <div class="image-round-gradation">
            <div class="height"></div>
        </div>
    </div>

app/views/shared/_jquery_without_login.html.erb
<% if !logged_in? %>
    <div class="image" id="fadeout-image">
        <div class="image-round-gradation">
            <div class="height"></div>
        </div>
    </div>
<% end %>

app/views/shared/_stats.html.erb
<div class="stats">
    <%= link_to "#{@user.following.count} following", user_following_path(@user) %>
    <%= link_to "#{@user.followers.count} followers", user_follower_path(@user) %>
</div>