config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get "/about",   to: "home#about"
  get "/help", to: "home#help"
  get "/contact", to: "home#contact"
  get "/terms", to: "home#terms"
  get "/signup",  to: "users#new"
  get "/signup", to: "users#create"
  get '/login', to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/search", to: "posts#search"

  resources :users, except: [:new, :create]

  resources :users do
    resource :password, except: [:index, :create, :new, :show , :destroy]
    resource :following, only: [:show]
    resource :follower, only: [:show]
    # member do
    #   get :following, :followers
    # end
  end

  resources :posts, except: [:index, :destroy] do
    resource :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: :index

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if logged_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed
    end
  end

  def about 
  end

  def help
  end

  def contact
  end

  def terms
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<% provide(:title, "About") %>
<div class="container">
    <div class="toppage-title">
        <h1>About us</h1>
    </div>
</div>

app/views/home/contact.html.erb
<% provide(:title, "Contact") %>
<div class="container">
    <div class="toppage-title">
        <h1>Contact</h1>
    </div>
</div>

app/views/home/help.html.erb
<% provide(:title, "Help") %>
<div class="container">
    <div class="toppage-title">
        <h1>Help</h1>
    </div>
</div>

app/views/home/terms.html.erb
<% provide(:title, "利用規約") %>
<div class="container">
    <div class="toppage-title">
        <h1>利用規約</h1>
    </div>
</div>

app/views/home/top.html.erb
<%= render 'shared/jquery_without_login' %>
  <div class="container">
      <div class="top-link">
        
      
        <% if logged_in? %>
          <div class="find-user">
            <%= link_to "友達を探す", users_path %>
          </div>
          <% if @feed_items.any? %>
         
            <% @feed_items.each do |feed_item| %>
            <div class="feed-wrapper">
              <div class="row">
                <div class="col-md-10 feed-image">
                  <%= link_to image_tag(feed_item.user.image.url, class: "image-size-middle"), feed_item.user %>
                  <div class="feed-image-name">
                    <%= link_to feed_item.user.name, feed_item.user %>
                  </div>
                </div>
              </div>
              <div class="row feed-main">
                <div class="col-md-3 feed-photo">
                  <%= link_to image_tag(feed_item.photo.url), feed_item %>
                </div>
                  <div class="col-md-8 feed-content">
                    <%= feed_item.content %>
                  </div>
              </div>
            </div>
            <% end %>
          <% end %> 
        <% else %>
          <div class="top-button">
            <div class="top-text">
              Let's leave memories.
            </div>
            <%= link_to "いますぐ始める!", signup_path , class: "btn-gradation" %>
            <%= link_to "ログインする", login_path , class: "btn-gradation" %>
            </div>
          </div>
        <% end %>
      </div>
  </div>