config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  get "/about",   to: "home#about"
  get "/help", to: "home#help"
  get "/contact", to: "home#contact"
  get "/terms", to: "home#terms"
  get "/signup",  to: "users#new"
  get "/signup", to: "users#create"
  get '/login', to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/search", to: "posts#search"

  resources :users, except: [:new, :create]

  resources :users do
    resource :password, except: [:index, :create, :new, :show , :destroy]
    resource :following, only: [:show]
    resource :follower, only: [:show]
    # member do
    #   get :following, :followers
    # end
  end

  resources :posts, except: [:index, :destroy] do
    resource :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: :index

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :notifications, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :photo, presence: true
  validates :content, presence: true, length: { maximum: 140}


  def self.search search
    return Post.all unless search
    Post.where(['content LIKE ?', "%#{search}%"])
  end



  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ",
                               current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(post_id: id,
                                                           visited_id: user_id,
                                                           action: 'like' )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end



  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end



  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(post_id: id,
                                                         comment_id: comment_id,
                                                        visited_id: visited_id,
                                                      action: 'comment')
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create] # destroyなし


  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments
    @comment = Comment.new
    # @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    # @user = User.find_by(id: session[:user_id])
    #          ↓current_userがあるおかげでログインしていないと投稿できない
    #            (@user.posts.buildと同じ)
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "posted your photo successfully!"
      redirect_to post_url @post
    else
      render "posts/new"
    end
  end


  # destroyなし
  def destroy
  end

  def search
    @word = params[:search]
    @posts = Post.search(params[:search])
  end



  private

    def post_params
      params.require(:post).permit(:content, :photo)
    end
   
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
<%= form_with(model: current_user.likes.build ,url: post_likes_url(@post), local: true, method: :post) do |f| %>
    <div><%= hidden_field_tag :post_id, @post.id %></div>
    <%= f.submit "いいね", class: "btn btn-width btn-danger" %>
<% end %>

app/views/posts/_like_form.html.erb
<% if current_user %>  
    <div class="a">
        <% if current_user.like?(@post) %>
            <%= render 'unlike'%>
        <% else %>
            <%= render 'like'%>
        <% end %>
    </div>
<% end %>

app/views/posts/_unlike.html.erb
<%= form_with(model: current_user.likes.find_by(post_id: @post.id), url: post_likes_url(@post), html: { method: :delete}, local: true) do |f| %>
    <%= f.submit "いいねを取り消す", class: "btn btn-width btn-danger" %>
<% end %>

app/views/posts/new.html.erb
<% provide(:title, "New Post")%>
<div class="container">
  <%= form_with model: @post, multipart: true, local: true  do |f| %>
    <%= render 'shared/@post_error_messages' %>
    <div class="form-wrapper">
      <ul>
        <div class="form-label">photo</div>
        <li>
          <%= f.label :photo, "画像を選択する", class: "btn-primary image-label fas fa-file-upload" %>
        </li>
        <li class="file-selection">
          <%= f.file_field :photo %>
        </li>
        <li class="form-label">
          <%= f.label :content %>
        </li>
        <li>
          <%= f.text_area :content%>
        </li>
        <li>
          <%= f.submit "Submit", class: "submit"%>
        </li>

      </ul>
    </div>
  <% end %>
</div>

app/views/posts/search.html.erb
<% provide(:title, @word) %>

<div class="container">
    <% @posts.each do |post| %>
        <div class="row user-border">
            <div class="col-md-2">
                <div class="username-limit">
                    <%= link_to username_limit(post.user.name), post.user %>
                </div>
                <%= link_to image_tag(post.user.image.url, class: "column-image" ),post.user  %>
            </div>
            <div class="col-md-4">
                <%= link_to image_tag(post.photo.url), post %>
            </div>
            <div class="col-md-6 search-content-wrapper">
                <div class="search-content">
                    <%= post.content %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<% provide(:title, characters_limit(@post))%>
<div class="container">
  <div class="each-image">
    <% if @post && @post.photo? %>
      <%= image_tag @post.photo.url, class: "user-post-image" %>
      <div class="user-post-text">
        <%= @post.content %>
      </div>
      <%= render 'like_form' %>
      <%= "#{@post.likes.count}いいね" %><i class="fas fa-thumbs-up"></i>
    <% else %>
      <div>投稿が見つかりません</div>
    <% end %>
  </div>
  <% if logged_in? %>
    <div class="post-form-wrapper">
      <%= form_with model: [@post, @comment], local: true  do |f| %>
        <%= f.text_area :content %>
        <%= f.submit "コメントを残す" %>
      <% end %>
    </div>
  <% end %>
  
　<div class="comment-wrapper">
    <% @comments.each do |comment| %>
      <div class="each-comment-wrapper">
        <div class="comment-icon">
          <div class="comment-icon-username">
            <%= comment.user.name %>
          </div>
          <%= link_to image_tag(comment.user.image.url, class: "image-size-small"), comment.user %>
        </div>
        <div class="comment-content">
          <%= comment.content %>
        </div>
        <% if comment.user == current_user  %>
          <%= button_to "delete", post_comments_path(comment), { method: :delete, data: { confirm: '削除しますか？' } } %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>